[2025-01-17 00:46:35,878] {taskinstance.py:897} INFO - Dependencies not met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model 2016-12-20T00:00:00+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2025-01-16T23:46:35.878436+00:00 and task will be retried at 2025-01-16T23:51:31.039214+00:00.
[2025-01-17 00:46:35,880] {local_task_job.py:96} INFO - Task is not able to be run
[2025-01-17 00:53:00,989] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model 2016-12-20T00:00:00+00:00 [queued]>
[2025-01-17 00:53:00,994] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model 2016-12-20T00:00:00+00:00 [queued]>
[2025-01-17 00:53:00,995] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2025-01-17 00:53:00,995] {taskinstance.py:1096} INFO - Starting attempt 2 of 4
[2025-01-17 00:53:00,995] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2025-01-17 00:53:01,016] {taskinstance.py:1115} INFO - Executing <Task(BashOperator): pyspark_train_classifier_model> on 2016-12-20T00:00:00+00:00
[2025-01-17 00:53:01,018] {standard_task_runner.py:52} INFO - Started process 345894 to run task
[2025-01-17 00:53:01,023] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'agile_data_science_batch_prediction_model_training', 'pyspark_train_classifier_model', '2016-12-20T00:00:00+00:00', '--job-id', '61', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmpjx_3jsk7', '--error-file', '/tmp/tmpxs2md15j']
[2025-01-17 00:53:01,024] {standard_task_runner.py:77} INFO - Job 61: Subtask pyspark_train_classifier_model
[2025-01-17 00:53:01,048] {logging_mixin.py:109} INFO - Running <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model 2016-12-20T00:00:00+00:00 [running]> on host ibdn-VirtualBox
[2025-01-17 00:53:01,073] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=agile_data_science_batch_prediction_model_training
AIRFLOW_CTX_TASK_ID=pyspark_train_classifier_model
AIRFLOW_CTX_EXECUTION_DATE=2016-12-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2016-12-20T00:00:00+00:00
[2025-01-17 00:53:01,073] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2025-01-17 00:53:01,074] {subprocess.py:63} INFO - Running command: ['bash', '-c', '\nspark-submit --master local[8]   /home/ibdn/BDFI/practica_creativa//resources/train_spark_mllib_model.py   /home/ibdn/BDFI/practica_creativa/']
[2025-01-17 00:53:01,078] {subprocess.py:74} INFO - Output:
[2025-01-17 00:53:02,917] {subprocess.py:78} INFO - 25/01/17 00:53:02 WARN Utils: Your hostname, ibdn-VirtualBox resolves to a loopback address: 127.0.1.1; using 10.0.2.15 instead (on interface enp0s3)
[2025-01-17 00:53:02,918] {subprocess.py:78} INFO - 25/01/17 00:53:02 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2025-01-17 00:53:03,578] {subprocess.py:78} INFO - 25/01/17 00:53:03 INFO SparkContext: Running Spark version 3.3.0
[2025-01-17 00:53:03,707] {subprocess.py:78} INFO - 25/01/17 00:53:03 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-01-17 00:53:03,857] {subprocess.py:78} INFO - 25/01/17 00:53:03 INFO ResourceUtils: ==============================================================
[2025-01-17 00:53:03,858] {subprocess.py:78} INFO - 25/01/17 00:53:03 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-01-17 00:53:03,859] {subprocess.py:78} INFO - 25/01/17 00:53:03 INFO ResourceUtils: ==============================================================
[2025-01-17 00:53:03,860] {subprocess.py:78} INFO - 25/01/17 00:53:03 INFO SparkContext: Submitted application: train_spark_mllib_model.py
[2025-01-17 00:53:03,885] {subprocess.py:78} INFO - 25/01/17 00:53:03 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-01-17 00:53:03,893] {subprocess.py:78} INFO - 25/01/17 00:53:03 INFO ResourceProfile: Limiting resource is cpu
[2025-01-17 00:53:03,894] {subprocess.py:78} INFO - 25/01/17 00:53:03 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-01-17 00:53:03,960] {subprocess.py:78} INFO - 25/01/17 00:53:03 INFO SecurityManager: Changing view acls to: ibdn
[2025-01-17 00:53:03,960] {subprocess.py:78} INFO - 25/01/17 00:53:03 INFO SecurityManager: Changing modify acls to: ibdn
[2025-01-17 00:53:03,960] {subprocess.py:78} INFO - 25/01/17 00:53:03 INFO SecurityManager: Changing view acls groups to:
[2025-01-17 00:53:03,960] {subprocess.py:78} INFO - 25/01/17 00:53:03 INFO SecurityManager: Changing modify acls groups to:
[2025-01-17 00:53:03,960] {subprocess.py:78} INFO - 25/01/17 00:53:03 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(ibdn); groups with view permissions: Set(); users  with modify permissions: Set(ibdn); groups with modify permissions: Set()
[2025-01-17 00:53:04,272] {subprocess.py:78} INFO - 25/01/17 00:53:04 INFO Utils: Successfully started service 'sparkDriver' on port 34715.
[2025-01-17 00:53:04,314] {subprocess.py:78} INFO - 25/01/17 00:53:04 INFO SparkEnv: Registering MapOutputTracker
[2025-01-17 00:53:04,353] {subprocess.py:78} INFO - 25/01/17 00:53:04 INFO SparkEnv: Registering BlockManagerMaster
[2025-01-17 00:53:04,433] {subprocess.py:78} INFO - 25/01/17 00:53:04 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-01-17 00:53:04,434] {subprocess.py:78} INFO - 25/01/17 00:53:04 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-01-17 00:53:04,446] {subprocess.py:78} INFO - 25/01/17 00:53:04 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-01-17 00:53:04,471] {subprocess.py:78} INFO - 25/01/17 00:53:04 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-8b7b1d79-9f05-4e6c-88ef-547408fadad4
[2025-01-17 00:53:04,503] {subprocess.py:78} INFO - 25/01/17 00:53:04 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-01-17 00:53:04,534] {subprocess.py:78} INFO - 25/01/17 00:53:04 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-01-17 00:53:04,861] {subprocess.py:78} INFO - 25/01/17 00:53:04 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-01-17 00:53:05,126] {subprocess.py:78} INFO - 25/01/17 00:53:05 INFO Executor: Starting executor ID driver on host 10.0.2.15
[2025-01-17 00:53:05,146] {subprocess.py:78} INFO - 25/01/17 00:53:05 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-01-17 00:53:05,183] {subprocess.py:78} INFO - 25/01/17 00:53:05 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 33177.
[2025-01-17 00:53:05,184] {subprocess.py:78} INFO - 25/01/17 00:53:05 INFO NettyBlockTransferService: Server created on 10.0.2.15:33177
[2025-01-17 00:53:05,186] {subprocess.py:78} INFO - 25/01/17 00:53:05 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-01-17 00:53:05,196] {subprocess.py:78} INFO - 25/01/17 00:53:05 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 10.0.2.15, 33177, None)
[2025-01-17 00:53:05,211] {subprocess.py:78} INFO - 25/01/17 00:53:05 INFO BlockManagerMasterEndpoint: Registering block manager 10.0.2.15:33177 with 434.4 MiB RAM, BlockManagerId(driver, 10.0.2.15, 33177, None)
[2025-01-17 00:53:05,219] {subprocess.py:78} INFO - 25/01/17 00:53:05 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 10.0.2.15, 33177, None)
[2025-01-17 00:53:05,220] {subprocess.py:78} INFO - 25/01/17 00:53:05 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 10.0.2.15, 33177, None)
[2025-01-17 00:53:05,913] {subprocess.py:78} INFO - 25/01/17 00:53:05 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-01-17 00:53:05,970] {subprocess.py:78} INFO - 25/01/17 00:53:05 INFO SharedState: Warehouse path is 'file:/tmp/airflowtmp5g1g2lz1/spark-warehouse'.
[2025-01-17 00:53:06,184] {local_task_job.py:204} WARNING - Recorded pid 346011 does not match the current pid 345894
[2025-01-17 00:53:06,206] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 345894
[2025-01-17 00:53:06,206] {taskinstance.py:1236} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-17 00:53:06,207] {subprocess.py:88} INFO - Sending SIGTERM signal to process group
[2025-01-17 00:53:06,210] {taskinstance.py:1463} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 171, in execute
    output_encoding=self.output_encoding,
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 76, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1238, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-01-17 00:53:06,220] {taskinstance.py:1513} INFO - Marking task as UP_FOR_RETRY. dag_id=agile_data_science_batch_prediction_model_training, task_id=pyspark_train_classifier_model, execution_date=20161220T000000, start_date=20250116T235303, end_date=20250116T235306
[2025-01-17 00:53:06,712] {process_utils.py:66} INFO - Process psutil.Process(pid=345894, status='terminated', exitcode=1, started='00:53:00') (345894) terminated with exit code 1
[2025-01-17 00:53:06,712] {process_utils.py:66} INFO - Process psutil.Process(pid=346006, status='terminated', started='00:53:02') (346006) terminated with exit code None
[2025-01-17 00:53:06,781] {process_utils.py:66} INFO - Process psutil.Process(pid=345895, status='terminated', started='00:53:00') (345895) terminated with exit code None
