[2025-01-17 00:41:23,316] {taskinstance.py:897} INFO - Dependencies not met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model 2016-12-17T00:00:00+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2025-01-16T23:41:23.316937+00:00 and task will be retried at 2025-01-16T23:46:11.952301+00:00.
[2025-01-17 00:41:23,319] {local_task_job.py:96} INFO - Task is not able to be run
[2025-01-17 00:46:29,086] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model 2016-12-17T00:00:00+00:00 [queued]>
[2025-01-17 00:46:29,094] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model 2016-12-17T00:00:00+00:00 [queued]>
[2025-01-17 00:46:29,096] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2025-01-17 00:46:29,107] {taskinstance.py:1096} INFO - Starting attempt 2 of 4
[2025-01-17 00:46:29,107] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2025-01-17 00:46:29,121] {taskinstance.py:1115} INFO - Executing <Task(BashOperator): pyspark_train_classifier_model> on 2016-12-17T00:00:00+00:00
[2025-01-17 00:46:29,123] {standard_task_runner.py:52} INFO - Started process 339793 to run task
[2025-01-17 00:46:29,130] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'agile_data_science_batch_prediction_model_training', 'pyspark_train_classifier_model', '2016-12-17T00:00:00+00:00', '--job-id', '53', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmptzmxeohr', '--error-file', '/tmp/tmpg52u9lfn']
[2025-01-17 00:46:29,131] {standard_task_runner.py:77} INFO - Job 53: Subtask pyspark_train_classifier_model
[2025-01-17 00:46:29,163] {logging_mixin.py:109} INFO - Running <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model 2016-12-17T00:00:00+00:00 [running]> on host ibdn-VirtualBox
[2025-01-17 00:46:29,193] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=agile_data_science_batch_prediction_model_training
AIRFLOW_CTX_TASK_ID=pyspark_train_classifier_model
AIRFLOW_CTX_EXECUTION_DATE=2016-12-17T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2016-12-17T00:00:00+00:00
[2025-01-17 00:46:29,193] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2025-01-17 00:46:29,194] {subprocess.py:63} INFO - Running command: ['bash', '-c', '\nspark-submit --master local[8]   /home/ibdn/BDFI/practica_creativa//resources/train_spark_mllib_model.py   /home/ibdn/BDFI/practica_creativa/']
[2025-01-17 00:46:29,208] {subprocess.py:74} INFO - Output:
[2025-01-17 00:46:31,473] {subprocess.py:78} INFO - 25/01/17 00:46:31 WARN Utils: Your hostname, ibdn-VirtualBox resolves to a loopback address: 127.0.1.1; using 10.0.2.15 instead (on interface enp0s3)
[2025-01-17 00:46:31,504] {subprocess.py:78} INFO - 25/01/17 00:46:31 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2025-01-17 00:46:32,495] {subprocess.py:78} INFO - 25/01/17 00:46:32 INFO SparkContext: Running Spark version 3.3.0
[2025-01-17 00:46:32,586] {subprocess.py:78} INFO - 25/01/17 00:46:32 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-01-17 00:46:32,813] {subprocess.py:78} INFO - 25/01/17 00:46:32 INFO ResourceUtils: ==============================================================
[2025-01-17 00:46:32,816] {subprocess.py:78} INFO - 25/01/17 00:46:32 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-01-17 00:46:32,819] {subprocess.py:78} INFO - 25/01/17 00:46:32 INFO ResourceUtils: ==============================================================
[2025-01-17 00:46:32,820] {subprocess.py:78} INFO - 25/01/17 00:46:32 INFO SparkContext: Submitted application: train_spark_mllib_model.py
[2025-01-17 00:46:32,853] {subprocess.py:78} INFO - 25/01/17 00:46:32 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-01-17 00:46:32,863] {subprocess.py:78} INFO - 25/01/17 00:46:32 INFO ResourceProfile: Limiting resource is cpu
[2025-01-17 00:46:32,865] {subprocess.py:78} INFO - 25/01/17 00:46:32 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-01-17 00:46:32,943] {subprocess.py:78} INFO - 25/01/17 00:46:32 INFO SecurityManager: Changing view acls to: ibdn
[2025-01-17 00:46:32,944] {subprocess.py:78} INFO - 25/01/17 00:46:32 INFO SecurityManager: Changing modify acls to: ibdn
[2025-01-17 00:46:32,946] {subprocess.py:78} INFO - 25/01/17 00:46:32 INFO SecurityManager: Changing view acls groups to:
[2025-01-17 00:46:32,966] {subprocess.py:78} INFO - 25/01/17 00:46:32 INFO SecurityManager: Changing modify acls groups to:
[2025-01-17 00:46:32,966] {subprocess.py:78} INFO - 25/01/17 00:46:32 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(ibdn); groups with view permissions: Set(); users  with modify permissions: Set(ibdn); groups with modify permissions: Set()
[2025-01-17 00:46:33,262] {subprocess.py:78} INFO - 25/01/17 00:46:33 INFO Utils: Successfully started service 'sparkDriver' on port 35727.
[2025-01-17 00:46:33,287] {subprocess.py:78} INFO - 25/01/17 00:46:33 INFO SparkEnv: Registering MapOutputTracker
[2025-01-17 00:46:33,377] {subprocess.py:78} INFO - 25/01/17 00:46:33 INFO SparkEnv: Registering BlockManagerMaster
[2025-01-17 00:46:33,414] {subprocess.py:78} INFO - 25/01/17 00:46:33 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-01-17 00:46:33,415] {subprocess.py:78} INFO - 25/01/17 00:46:33 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-01-17 00:46:33,435] {subprocess.py:78} INFO - 25/01/17 00:46:33 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-01-17 00:46:33,459] {subprocess.py:78} INFO - 25/01/17 00:46:33 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-b458d253-fd4c-49ff-bc15-1f2bd879bb71
[2025-01-17 00:46:33,486] {subprocess.py:78} INFO - 25/01/17 00:46:33 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-01-17 00:46:33,517] {subprocess.py:78} INFO - 25/01/17 00:46:33 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-01-17 00:46:33,843] {subprocess.py:78} INFO - 25/01/17 00:46:33 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-01-17 00:46:34,027] {subprocess.py:78} INFO - 25/01/17 00:46:34 INFO Executor: Starting executor ID driver on host 10.0.2.15
[2025-01-17 00:46:34,045] {subprocess.py:78} INFO - 25/01/17 00:46:34 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-01-17 00:46:34,073] {subprocess.py:78} INFO - 25/01/17 00:46:34 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 36005.
[2025-01-17 00:46:34,074] {subprocess.py:78} INFO - 25/01/17 00:46:34 INFO NettyBlockTransferService: Server created on 10.0.2.15:36005
[2025-01-17 00:46:34,075] {subprocess.py:78} INFO - 25/01/17 00:46:34 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-01-17 00:46:34,089] {subprocess.py:78} INFO - 25/01/17 00:46:34 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 10.0.2.15, 36005, None)
[2025-01-17 00:46:34,099] {subprocess.py:78} INFO - 25/01/17 00:46:34 INFO BlockManagerMasterEndpoint: Registering block manager 10.0.2.15:36005 with 434.4 MiB RAM, BlockManagerId(driver, 10.0.2.15, 36005, None)
[2025-01-17 00:46:34,107] {subprocess.py:78} INFO - 25/01/17 00:46:34 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 10.0.2.15, 36005, None)
[2025-01-17 00:46:34,107] {subprocess.py:78} INFO - 25/01/17 00:46:34 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 10.0.2.15, 36005, None)
[2025-01-17 00:46:34,144] {local_task_job.py:204} WARNING - Recorded pid 339932 does not match the current pid 339793
[2025-01-17 00:46:34,172] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 339793
[2025-01-17 00:46:34,173] {taskinstance.py:1236} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-17 00:46:34,173] {subprocess.py:88} INFO - Sending SIGTERM signal to process group
[2025-01-17 00:46:34,176] {process_utils.py:66} INFO - Process psutil.Process(pid=339901, status='terminated', started='00:46:31') (339901) terminated with exit code None
[2025-01-17 00:46:34,179] {taskinstance.py:1463} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 171, in execute
    output_encoding=self.output_encoding,
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 76, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1238, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-01-17 00:46:34,190] {taskinstance.py:1513} INFO - Marking task as UP_FOR_RETRY. dag_id=agile_data_science_batch_prediction_model_training, task_id=pyspark_train_classifier_model, execution_date=20161217T000000, start_date=20250116T234633, end_date=20250116T234634
[2025-01-17 00:46:34,538] {process_utils.py:66} INFO - Process psutil.Process(pid=339793, status='terminated', exitcode=1, started='00:46:28') (339793) terminated with exit code 1
[2025-01-17 00:46:34,779] {process_utils.py:66} INFO - Process psutil.Process(pid=339794, status='terminated', started='00:46:28') (339794) terminated with exit code None
